### PR TITLE
mention ipfs experimental nocopy import

### PR DESCRIPTION
**Pull request by anarcat**
It turns out that IPFS doesn't necessarily duplicate storage anymore, even though that's an experimental feature.

### CODE REVIEW

**Comment by chartgerink** [comment]
Seems like the link is incorrect?
https://github.com/datproject/docs/issues/110

**Comment by anarcat** [comment]
oops, indeed - bad copy/paste.

**Comment by anarcat** [comment]
@chartgerink fixed.

**Comment by joehand** [comment]
Thanks!

**Pull request merged**
