### PR TITLE
Add "Bitfield RLE" section to Hyperdrive spec

### PR DESCRIPTION
**Pull request by pfrazee**
This will need to be double-checked by @mafintosh

### CODE REVIEW

**Comment by mafintosh** [comment]
The 'start' index is delta packed as well as far as I remember to save space (delta = start - prev-start)

**Comment by mafintosh** [comment]
yup just verified that

**Comment by pfrazee** [comment]
Ah ok, I'll edit that

**Comment by pfrazee** [comment]
Updated @mafintosh

**Comment by joehand** [comment]
Closing, we integrated most of this into the paper and removed this spec file for now. We plan to work on an implementation guide to replace this.

**Pull request closed without merging**
